### ISSUE TITLE
Crashes Domoticz 2020.2 (build 12377)

### ISSUE THREAD

**Issue by frontfoto** [nonolk/domoticz_tahoma_blind#12] opened 2020-09-07 15:41 UTC
Server: Ubuntu Linux
Version of domoticz: 2020.2 (build 12377)

The plugin seems to work with the stable version 2020.2 without crashes. It crashes and disconnects the plugin and when trying to update hardware to restart the thread it crashes. More info https://domoticz.com/forum/viewtopic.php?f=6&t=33874

Don't know if there's a faulty thing in this plugin or if the fault is within the domoticz beta.

**Comment by nonolk** [comment] 2020-09-08 09:18
Hello Frontfoto,

Could you please provide a bit more details ?
Like the version of ubuntu your are using and the platform on which it runs ? (ARM, x86_64.... )

As I'm also using a Domoticz beta version (12313) without any issues on my Raspberry pi3, with Buster and python 3.7.

One main diffrence between my plugin and the deconz one you are using, Is that my plugin use Domoticz to handle all the http connections (the other one manage it by itself), as recommended by the Domoticz [wiki](https://www.domoticz.com/wiki/Developing_a_Python_plugin#Connections)

Then I will try to reproduce the problem on my side.

Best regards,

**Comment by frontfoto** [comment] 2020-09-08 15:43
Hello nonolk,

The system is running on build 12377, and tried the latest of those as well. I had your plugin working before but for some update ago it started to misbehave.  The system I'm running it under is a proxmox pve installation with a VM that's running Linux.

Distributor ID: Ubuntu
Description:    Ubuntu 20.04.1 LTS
Release:        20.04
Codename:       focal

The system is running x86_64. I can't manage to run your plugin stable and one beta version of domoticz. Without any other plugin loaded. The system runs python 3.8.2 but I have also tried it running on recommended version. But it seems to run nice on Debian buster (also on pve, inside a lxc container) but with same kind of behaviour. If I go beta then it crashes. Some thoughts I got is that it somehow is connected to running in a VM, but it seems stable on 2020.2 version. A pattern I've seen when it crashes is that it happens after a command is sent to somfy/tahoma. Have I missed some data, perhaps that might help you in tracking the trouble down. It seems like domoticz have changed something that makes u'r plugin fail. Would  love to get a stable connections to my screens. Today they managed to go out but when the wind was rising they didn't go in again.

best regard,
Mattias

**Comment by frontfoto** [comment] 2020-09-09 19:05
Hi again,

I checked my test server right now. And the plugin has managed to survive and cooperate over 24 hours on a stable Domoticz release, 2020.2 without any crashes. But as soon as I upgrade the domoticz server to a recent beta. So it seems like it's working in a VM as well.

best regards,
Mattias

**Comment by frontfoto** [comment] 2020-09-10 17:42
2 days and counting. No idea how to take it further in testing.

**Comment by nonolk** [comment] 2020-09-10 18:12
For me it definitely comes from the latest beta version of Domoticz and the plugin. I will try to debug it further, but as it works for the stable version, I will not push it with high priority. But I will troubleshoot it for sure

**Comment by frontfoto** [comment] 2020-09-10 19:20
I think that something in this commit is involved in why your plugin crashes. https://github.com/domoticz/domoticz/commit/316c9b7c7

**Comment by frontfoto** [comment] 2020-09-14 19:58
> I think that something in this commit is involved in why your plugin crashes. [domoticz/domoticz@316c9b7](https://github.com/domoticz/domoticz/commit/316c9b7c7)

Haven't t found what's causing it.

**Comment by nonolk** [comment] 2020-10-26 17:50
Hello could you please update to the latest beta version fo both domoticz and the plugin.

For the plugin use git clone -b Test https://github.com/nonolk/domoticz_tahoma_blind.git

I'm running this version in an ubuntu 20.04.1 LTS vm without any issues for nearly a week.
I've update to the very latest beta version of Domoticz today and it seem to work also fine.

Best regards,

**Comment by mattias-nti** [comment] 2020-10-26 18:06
Updated my server to latest domoticz beta and updated the system it self. Cloned the Test version and started testing. Will give feedback when It has been up for a while. Tried to find another solution but haven't got any else working good either. So if this changes has fixed it, I would be very happy. Thanks for the effort.

**Comment by mattias-nti** [comment] 2020-11-06 16:12
Haven't got any crashes with the plugin. For some time it seems like it logged out of the service and when I try to remote control my devices they doesn't answer for a while. I'm not sure if it's connected to bad internet connection because my connection is little unstable.

**Comment by nonolk** [comment] 2020-11-06 16:35
@mattias-nti as it is a cloud based solution, if you have internet issue you may encounter some strange behaviour, like the one you got. Sadly I can nothing for this. As the crash issue seems to be resolved, I close this issue. Thank you for reporting back.

**Closed as completed by nonolk** 2020-11-06 16:35 UTC
